---
extends: default
rules:
  line-length:
    max: 120
  truthy:
    allowed-values: ['true', 'false', 'on', 'off']
  empty-values:
    forbid-in-block-mappings: true
  octal-values:
    forbid-implicit-octal: true
  comments:
    min-spaces-from-content: 1